CREATE TABLE EMPLOYEE(

id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR,
last_name VARCHAR,
age INT,
insert_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

--CREATE TABLE SALARY(
--
--id INT PRIMARY KEY AUTO_INCREMENT,
--employee_id INT ,
--salary INT,
--inserted_date TIMESTAMP DEFAULT CURRENT_DATE,
--FOREIGN KEY (employee_id) REFERENCES EMPLOYEE (id)
--
--);
--
--CREATE TABLE OFFICE(
--id PRIMARY KEY AUTO_INCREMENT,
--name VARCHAR,
--city VARCHAR,
--office_id INT,
--FOREIGN KEY (office_id) REFERENCES EMPLOYEE (id)
--);